### ISSUE TITLE
Add Webpack 2.0 support

### ISSUE THREAD

**Issue by splodingsocks** [cultureamp/elm-css-modules-loader#1]
@sentience this is super duper cool! Thanks for providing it! I noticed in the ReadMe that Webpack 2.0 support is at the top of the priority list. I wanted to follow progress right away, but I didn't find an issue for it, so I made this one. I hope that's okay!

**Comment by sentience** [comment]
Thanks, @splodingsocks!

**Comment by jasononeil** [comment]
This was added some time ago (in e8284b5fd8abdc1602a0daad6a3063973b09411b) and is available in v1.1.2 and 2.0.0+

I'll close this now :)
