### ISSUE TITLE
hypens

### ISSUE THREAD

**Issue by kurtharriger** [cultureamp/elm-css-modules-loader#18]
was trying to migrate some existing css and although its easy to use hyphens in the elm string it blows up on the hyphen when translated to js.  

fixedTop: require("./WelcomePage.module.css").fixed-top,

**Comment by jasononeil** [comment]
Thanks for reporting! Should be an easy fix, @zioroboco is going to look into it

**Comment by zioroboco** [comment]
Fixed from v3.0.2 of the loader
