### ISSUE TITLE
Getting example app to work?

### ISSUE THREAD

**Issue by harfangk** [cultureamp/elm-css-modules-loader#20]
Hi, I tried to run example app to see the exact output, but couldn't get it working.

I tried:
```
git clone git@github.com:cultureamp/elm-css-modules-loader.git
cd elm-css-modules-loader/example
yarn
elm-live elm-app/Main.elm
```

The app compiles and launches successfully. I can see the texts, but styles were not applied. Is there something I'm missing? I also tried `elm reactor` but it had identical result.

I'm using Elm 0.19 and NodeJS 9.0 on Ubuntu 16.04

**Comment by Hisamera** [comment]
I can also atest that example app doesn't work, I got "ERROR in ./elm-app/Main.elm
Module build failed: Error: Cannot find module 'loader-utils' (...)", but I'm starting my web dev carrer so I could also made a mistake somewhere (Dunno where though, just downloaded and tried to execute it)

**Comment by Hisamera** [comment]
After few hours of trial and error I found out that dependencies were to blame right now my package.json looks like this
```
"webpack-cli": "^3.2.3",
"css-loader": "^2.1.0",
"elm": "^0.19.0-bugfix2",
"elm-css-modules-loader": "^3.0.4",
"elm-webpack-loader": "^5.0.0",
"style-loader": "^0.23.1",
 "webpack": "^4.29.5"
```
It's my suspicion that these lines are to blame "elm-webpack-loader": "xtian/elm-webpack-loader#0.19" and "elm-css-modules-loader": "file:.."
But it now miraculously works, now to pinpoint where I made a mistake in my project...
