### ISSUE TITLE
Change Help Function Names to avoid Conflict with Html.Attributes

### ISSUE THREAD

**Issue by NickSpinosa** [cultureamp/elm-css-modules-loader#5]
would suggest changing `class` to className in order to support using both global and modular css. obvious use case is using a css framework like bootstrap

**Comment by ivanbanov** [comment]
To avoid this conflict I just doing things like this
```elm
import Html exposing (..)
import Html.Attributes exposing (..)
import Styles

view : Html msg
view =
    div
        [ class "foo"
        , Styles.class .myClass
        ]
```

**Comment by MichaelCombs28** [comment]
I think module namespacing for non standard modules is a good idea regardless of the naming scheme.
Styles.class is a well named identifier and should stick imo. It's concise and either way importing attributes with an expose all could end up making your code hard to read in the future. Slight verbosity makes readability & maintenance easier. 

 Good job on the package!
